// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnz8yIYVratUL5nvGSt7zFrsjFDbYpAA',
    appId: '1:29742879658:web:fe4ceff07f69c14dc811d3',
    messagingSenderId: '29742879658',
    projectId: 'social-media-f22be',
    authDomain: 'social-media-f22be.firebaseapp.com',
    storageBucket: 'social-media-f22be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZ7XO2CMKji8KF5nsDZ_5gL-E6b066oE',
    appId: '1:29742879658:android:745f2768c5167b0ac811d3',
    messagingSenderId: '29742879658',
    projectId: 'social-media-f22be',
    storageBucket: 'social-media-f22be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhI6VttY7AC6bh170pyfqcD_87XZcHJM',
    appId: '1:29742879658:ios:217da0a735f50968c811d3',
    messagingSenderId: '29742879658',
    projectId: 'social-media-f22be',
    storageBucket: 'social-media-f22be.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXhI6VttY7AC6bh170pyfqcD_87XZcHJM',
    appId: '1:29742879658:ios:217da0a735f50968c811d3',
    messagingSenderId: '29742879658',
    projectId: 'social-media-f22be',
    storageBucket: 'social-media-f22be.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnz8yIYVratUL5nvGSt7zFrsjFDbYpAA',
    appId: '1:29742879658:web:073e42bb4f0da176c811d3',
    messagingSenderId: '29742879658',
    projectId: 'social-media-f22be',
    authDomain: 'social-media-f22be.firebaseapp.com',
    storageBucket: 'social-media-f22be.firebasestorage.app',
  );

}