// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxRfVKRbarqSiDQNcHruWU8_6JxjNtPk',
    appId: '1:1061269423415:web:0980918564a56323e786b2',
    messagingSenderId: '1061269423415',
    projectId: 'social-media-2bfbf',
    authDomain: 'social-media-2bfbf.firebaseapp.com',
    storageBucket: 'social-media-2bfbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCWLezK44aO9jI05ZN8my8ikJMG4maKo',
    appId: '1:1061269423415:android:ecf20f0374d00de4e786b2',
    messagingSenderId: '1061269423415',
    projectId: 'social-media-2bfbf',
    storageBucket: 'social-media-2bfbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXr-nuc7jxcmqybNavgPP6Wvquy9jv-A',
    appId: '1:1061269423415:ios:0e454ee46ae68382e786b2',
    messagingSenderId: '1061269423415',
    projectId: 'social-media-2bfbf',
    storageBucket: 'social-media-2bfbf.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAXr-nuc7jxcmqybNavgPP6Wvquy9jv-A',
    appId: '1:1061269423415:ios:0e454ee46ae68382e786b2',
    messagingSenderId: '1061269423415',
    projectId: 'social-media-2bfbf',
    storageBucket: 'social-media-2bfbf.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGxRfVKRbarqSiDQNcHruWU8_6JxjNtPk',
    appId: '1:1061269423415:web:1be4879cb8731f67e786b2',
    messagingSenderId: '1061269423415',
    projectId: 'social-media-2bfbf',
    authDomain: 'social-media-2bfbf.firebaseapp.com',
    storageBucket: 'social-media-2bfbf.firebasestorage.app',
  );
}
